
function [data1,data2,data3,data4,data5,data6,data7,data8,data9,data10]=Feclogg(a,b,u,h,k0,poroini,O2,c,fe2,t0,tmax,an,bn,rw)

% ******************** ******************************************************
tt=linspace(0,tmax,tmax*5+1);       % Temporal step,[h]
rho_bulk=1.77e6;           % Bulk density, [g/m3]
fe3=0;                       %mg/l
ph=7;
pfe=3.4;                     %g/cm3
kt=k0;
att=500;           %d-
det=0.94;
sigma=0.0011;              %m^3/kg
c0=0;
xx=linspace(rw,b+rw,bn+1);
yy=linspace(0,a,an+1);
[x,y] = meshgrid(xx,yy);
xy = [x(:),y(:)]';
Time_num=length(tt);
x_num=(an+1)*(bn+1);
%Develop r-axis
%Define initial condition
%********************** Using ODE under FOR LOOP   ************************
%********** Size setup for each parameter***************

%
C10=zeros(Time_num,x_num);
C11=zeros(Time_num,x_num);
KT=zeros(Time_num,x_num);
PH=zeros(Time_num,x_num);
FE2=zeros(Time_num,x_num);
FE3=zeros(Time_num,x_num);
PO=zeros(Time_num,x_num);
C20=zeros(Time_num,x_num);
C21=zeros(Time_num,x_num);
CS=zeros(Time_num,x_num);
CST=zeros(Time_num,x_num);
HP=zeros(Time_num,x_num);
C11(1,:)=O2;
C10(1,:)=0;%intc
C20(1,:)=c;%intc
C21(1,:)=0;
KT(1,:)=kt;
PO(1,:)=poroini;
PH(1,:)=ph;
CS(1,:)=0;
CST(1,:)=0;
HP(1,:)=0;
FE2(1,:)=fe2;
t0=tt(1);
t1=tt(2);
data=commodel(a,b,u,h,kt,poroini,c0,O2,c,t0,t1,xy,att,det,rw);
k=0;
%*********************************************************
    %c,n,k,H,cO2,cs,cst
 for iTime=1:Time_num-1
     t0=tt(iTime);
     t1=tt(iTime+1); 
    [num,~]=size(data); 
%     xlswrite('noteco51.xlsx',[data(:,1),data(:,2),data(:,3)]);
% PO(iTime+1,:)=data(:,4)';
    C10(iTime+1,:)=data(:,3)';
    PO(iTime+1,:)=data(:,4)';
    KT(iTime+1,:)=data(:,5)';
    HP(iTime+1,:)=data(:,6)';
    C20(iTime+1,:)=data(:,7)';
    CS(iTime+1,:)=data(:,8)';
    CST(iTime+1,:)=data(:,9)';
    PH(iTime+1,:)=PH(iTime,:);
    FE2(iTime+1,:)=FE2(iTime,:);
    FE3(iTime+1,:)=FE3(iTime,:);
%     ph=7;%ph=PH(iTime,ix);%
    for ix=1:num
%          ph=7;
        ph=PH(iTime,ix);
        dt=t1-t0;
        o2=data(ix,7);
        po=data(ix,4);
        kt=data(ix,5);
        hp=data(ix,6);
        Fe3=FE3(iTime,ix);%FE3(iTime,ix);
        Fe2=FE2(iTime,ix);
           che=fereaction(Fe2,Fe3,ph,o2*32,dt);
           dtn(iTime+1,ix)=che{12,5}(1,1)*107/56;
           PH(iTime+1,ix)=che{12,6}(1,1);
           FE2(iTime+1,ix)=che{12,4}(1,1);%mg/l 
           FE3(iTime+1,ix)=che{12,5}(1,1); %mol/m3+FE3(iTime,ix)
           C20(iTime+1,ix)=che{12,7}(1,1)/32;
%            CS(iTime+1,ix)=0.001*dtn(iTime+1,ix)/pfe/sigma+data(ix,8);  
           poo=po-0.001*dtn(iTime+1,ix)/pfe;
           r=poo^3*(1-po)^2/(1-poo)^2/po^3;         
           ktt=kt*r;
           PO(iTime+1,ix)=poo;
           KT(iTime+1,ix)=ktt;
           CS(iTime+1,ix)=(poroini-poo)/0.0011;
%            ph=PH(iTime,ix);
    end


% CC0(iTime+1,1:num);
% KT(iTime+1,1:num);
% PO(iTime+1,1:num);

ty1=reshape(C10(iTime+1,1:num),an+1,bn+1);
ty2=reshape(KT(iTime+1,1:num),an+1,bn+1);
ty3=reshape(PO(iTime+1,1:num),an+1,bn+1);
ty4=reshape(HP(iTime+1,1:num),an+1,bn+1);
ty5=reshape(C20(iTime+1,1:num),an+1,bn+1);
ty6=reshape(CS(iTime+1,1:num),an+1,bn+1);
ty7=reshape(CST(iTime+1,1:num),an+1,bn+1);
x=xx(1:bn+1);
y=yy(1:an+1);

mphinterpolationfile('noteco.txt','sectionwise',ty1,x,y);
mphinterpolationfile('notekt.txt','sectionwise',ty2,x,y);
mphinterpolationfile('notepo.txt','sectionwise',ty3,x,y);
mphinterpolationfile('notehp.txt','sectionwise',ty4,x,y);
mphinterpolationfile('noteco2.txt','sectionwise',ty5,x,y);
mphinterpolationfile('notecs.txt','sectionwise',ty6,x,y);
mphinterpolationfile('notecst.txt','sectionwise',ty7,x,y);
  data=commodel2(a,b,u,h,kt,poroini,c0,O2,c,t0,t1,xy,att,det,rw);
        k=k+1

%    delete notepo.xlsx
end
% KT
data1=KT;
data2=PO;
data3=C10;
data4=CS;
data5=CST;
data6=FE2;
data7=FE3;
data8=C20;
data9=HP;
data10=PH;

xlswrite('kt5.xlsx',KT);
xlswrite('PO.xlsx',PO);
xlswrite('fe25.xlsx',FE2);
xlswrite('fe35.xlsx',FE3);
xlswrite('PH5.xlsx',PH);
xlswrite('cco.xlsx', C10);
xlswrite('HP.xlsx', HP);
xlswrite('dtn.xlsx', dtn);
end
% PHH
% PH2
% PH3
%**************************************************************************
%**************************************************************************


%=======================    flow field   =================================
%a,b,u,h,kt,poroini,c0,O2,c,t0,t1,xy,att,det,rw)
function flow=commodel(a,b,u,h,kt,po,c0,c1,c2,t0,t1,xx,att,det,rw)
model = mphopen('fe1');
model.param.set('rx',[num2str(b),'[m]']);
model.param.set('rh',[num2str(a),'[m]']);
model.param.set('H',[num2str(h),'[m]']);
model.param.set('rw',[num2str(rw),'[m]']);
model.param.set('u',[num2str(u),'[ml/min]']);
model.param.set('po', po);
model.param.set('k0',[num2str(kt),'[m/s]']);
model.param.set('t0',[num2str(t0),'[h]']);
model.param.set('t1', [num2str(t1),'[h]']);
model.param.set('c0', [num2str(c0),'[mol/m^3]']);
model.param.set('c1', [num2str(c1),'[mol/m^3]']);
model.param.set('int_c', [num2str(c2),'[kg/m^3]']);
model.param.set('att', [num2str(att),'[d^-1]']);
model.param.set('det', [num2str(det),'[d^-1]']);

model.study('std1').run();
data1= mphinterp(model,'c','coord',xx);%o2
data2= mphinterp(model,'n','coord',xx);
data3= mphinterp(model,'K','coord',xx);
data4= mphinterp(model,'dl.Hp','coord',xx);
data5= mphinterp(model,'c2','coord',xx);%int_c
data6= mphinterp(model,'C_s','coord',xx);
data7= mphinterp(model,'C_st','coord',xx);

dt=floor((t1-t0)*10+1);
coo1=data1(dt,:);
coo2=data2(dt,:);
coo3=data3(dt,:);
coo4=data4(dt,:);
coo5=data5(dt,:);
coo6=data6(dt,:);
coo7=data7(dt,:);
% data8= mphinterp(model,'int2','coord');
% tbl=mphtable(model,'tbl2');
% data8=tbl.data;
% Q=data7()
flow=[xx',coo1',coo2',coo3',coo4',coo5',coo6',coo7'];
end
%a,b,u,h,kt,poroini,c0,O2,c,t0,t1,xy,att,det,rw)
function flow2=commodel2(a,b,u,h,kt,po,c0,c1,c2,t0,t1,xx,att,det,rw)%a,b,u,h,O2,c2,t0,t1,xy,att,det
model = mphopen('fe2');
model.param.set('rx',[num2str(b),'[m]']);%0.75
model.param.set('rh',[num2str(a),'[m]']);%0.2
model.param.set('u',[num2str(u),'[ml/min]']);
model.param.set('rw',[num2str(rw),'[m]']);
model.param.set('H',[num2str(h),'[m]']);
model.param.set('t0',[num2str(t0),'[h]']);
model.param.set('t1', [num2str(t1),'[h]']);
model.param.set('po', po);
model.param.set('k0',[num2str(kt),'[m/s]']);
% model.param.set('c0', [num2str(c0),'[mg/L]']);
model.param.set('c1', [num2str(c1),'[mol/m^3]']);
model.param.set('int_c', [num2str(c2),'[kg/m^3]']);
model.param.set('att', [num2str(att),'[d^-1]']);
model.param.set('det', [num2str(det),'[d^-1]']);

model.func('int1').discardData;
model.func('int1').importData;
% model.func('int4').discardData;
% model.func('int4').importData;
model.func('int2').discardData;
model.func('int2').importData;
model.func('int3').discardData;
model.func('int3').importData;
model.func('int4').discardData;
model.func('int4').importData;
model.func('int5').discardData;
model.func('int5').importData;
model.func('int6').discardData;
model.func('int6').importData;
model.func('int7').discardData;
model.func('int7').importData;
model.study('std1').run();
data1= mphinterp(model,'c','coord',xx);
data2= mphinterp(model,'n','coord',xx);
data3= mphinterp(model,'K','coord',xx);
data4= mphinterp(model,'dl.Hp','coord',xx);
data5= mphinterp(model,'c2','coord',xx);
data6= mphinterp(model,'C_s','coord',xx);
data7= mphinterp(model,'C_st','coord',xx);
dt=floor((t1-t0)*10+1);
coo1=data1(dt,:);
coo2=data2(dt,:);
coo3=data3(dt,:);
coo4=data4(dt,:);
coo5=data5(dt,:);
coo6=data6(dt,:);
coo7=data7(dt,:);
flow2=[xx',coo1',coo2',coo3',coo4',coo5',coo6',coo7'];
end


%========================bioreaction and source sink=======================
function che=fereaction(fe2,fe3,PH,o2,dt) 
iphreeqc = actxserver('IPhreeqcCOM.Object');
iphreeqc.LoadDatabase('E:\IPHREEQCCOM\database\phreeqc.dat'); 
IPCstringCell={
'SOLUTION_MASTER_SPECIES',  ...
'Fe_di              Fe_di+2    0.0     Fe_di              55.847',  ...
'Fe_tri             Fe_tri+3   0.0     Fe_tri             55.847',  ...           
'SOLUTION_SPECIES',  ...
'Fe_di+2 = Fe_di+2',  ...
        'log_k   0.0',  ...
'Fe_tri+3 = Fe_tri+3',  ...
        'log_k   0.0',  ...
'Fe_di+2 + Cl- = Fe_diCl+',  ...
        'log_k   0.14',  ...
'Fe_di+2 + CO3-2 = Fe_diCO3',  ...
        'log_k   4.38',  ...
'Fe_di+2 + HCO3- = Fe_diHCO3+ ',  ...
         'log_k   2.0',  ...
'Fe_di+2 + SO4-2 = Fe_diSO4',  ...
        'log_k   2.25',  ...
        'delta_h 3.230   kcal',  ...
'Fe_di+2 + HSO4- = Fe_diHSO4+',  ...
        'log_k   1.08',  ...
'Fe_di+2 + 2HS- = Fe_di(HS)2',  ...
        'log_k   8.95',  ...
'Fe_di+2 + 3HS- = Fe_di(HS)3-',  ...
        'log_k   10.987',  ...
'Fe_di+2 + HPO4-2 = Fe_diHPO4',  ...
        'log_k   3.6',  ...
'Fe_di+2 + H2PO4- = Fe_diH2PO4+',  ...
        'log_k   2.7',  ...
'Fe_di+2 + F- = Fe_diF+',  ...
        'log_k   1.0',  ...
'Fe_di+2 + H2O = Fe_diOH+ + H+',  ...
        'log_k   -9.5',  ...
        'delta_h 13.20 kcal',  ...
'# Fe+3 species',  ...
'Fe_tri+3 + H2O = Fe_triOH+2 + H+',  ...
        'log_k   -2.19',  ...
        'delta_h  10.4 kcal',  ...
'#... and also other Fe+3 species',  ...
'Fe_tri+3 + 2 H2O = Fe_tri(OH)2+ + 2 H+',  ...
        'log_k   -5.67',  ...
        'delta_h 17.1 kcal',  ...
'Fe_tri+3 + 3 H2O = Fe_tri(OH)3 + 3 H+',  ...
       ' log_k   -12.56',  ...
        'delta_h 24.8 kcal',  ...
'Fe_tri+3 + 4 H2O = Fe_tri(OH)4- + 4 H+',  ...
        'log_k   -21.6',  ...
        'delta_h 31.9 kcal',  ...
'2 Fe_tri+3 + 2 H2O = Fe_tri2(OH)2+4 + 2 H+',  ...
        'log_k   -2.95',  ...
        'delta_h 13.5 kcal',  ...
'3 Fe_tri+3 + 4 H2O = Fe_tri3(OH)4+5 + 4 H+',  ...
        'log_k   -6.3',  ...
        'delta_h 14.3 kcal',  ...
'Fe_tri+3 + Cl- = Fe_triCl+2',  ...
        'log_k   1.48',  ...
        'delta_h 5.6 kcal',  ...
'Fe_tri+3 + 2 Cl- = Fe_triCl2+',  ...
        'log_k   2.13',  ...
'Fe_tri+3 + 3 Cl- = Fe_triCl3',  ...
        'log_k   1.13',  ...
'Fe_tri+3 + SO4-2 = Fe_triSO4+',  ...
        'log_k   4.04',  ...
        'delta_h 3.91 kcal',  ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
'Fe_tri+3 + HSO4- = Fe_triHSO4+2',  ...
        'log_k   2.48',  ...               
'Fe_tri+3 + 2SO4-2 = Fe_tri(SO4)2-',  ...
        'log_k   5.38',  ...
        'delta_h 4.60    kcal',  ...
'Fe_tri+3 + HPO4-2 = Fe_triHPO4+',  ...
        'log_k   5.43',  ...
        'delta_h 5.76 kcal',  ...
'Fe_tri+3 + H2PO4- = Fe_triH2PO4+2',  ...
        'log_k   5.43',  ...
'Fe_tri+3 + F- = Fe_triF+2',  ...
        'log_k   6.2',  ...
        'delta_h 2.7     kcal',  ...
'Fe_tri+3 + 2 F- = Fe_triF2+',  ...
        'log_k   10.8',  ...
        'delta_h 4.8 kcal',  ...
'Fe_tri+3 + 3 F- = Fe_triF3',  ...
        'log_k   14.0',  ...
       'delta_h    5.4 kcal',  ...
'PHASES',  ... 
'Goethite',  ... 
   ' Fe_triOOH + 3H+ = Fe_tri+3 + 2H2O',  ... 
    'log_k     -1',  ... 
'Fe_tri(OH)3(a)',  ... 
    'Fe_tri(OH)3 + 3 H+ = Fe_tri+3 + 3 H2O',  ... 
    'log_k     4.891',  ... 
'END',  ... 
'SOLUTION 1',  ... 
    'temp      25',  ... 
     ['pH   ',    num2str(PH)], ...
    'pe        4', ...  
    ['O(0) ' ,num2str(o2)],  ... 
   ' redox     pe',  ... 
    'units     mg/l',  ... 
    'density   1',  ...
    ['Fe_di   ',num2str(fe2)], ...
    [ 'Fe_tri  ',num2str(fe3)], ... 
   ' -water    1 # kg',  ... ·
 'RATES',  ... 
    'Fe_di_ox',  ... 
'-start',  ... 
 '10 Fe_di = TOT("Fe_di")',  ... 
 '20 if (Fe_di <= 0) then goto 200',  ... 
 '30 p_o2 =  SR("O2(g)")',  ... 
' 40 moles = (2.91e-9 + 1.33e12 * (ACT("OH-"))^2 * p_o2) * Fe_di * TIME',  ... 
'200 SAVE moles',  ... 
'-end',  ... 
'KINETICS 1',  ... 
'Fe_di_ox',  ... 
    '-formula  Fe_di  -1 Fe_tri  1',  ...
    ' -m        1',  ...
    ' -m0       1',  ...
    '-tol      1e-008'...
['-steps '       num2str(dt*60) ' in 10 steps # seconds'],  ... 
'-step_divide 1',  ... 
'-runge_kutta 3',  ... 
'-bad_step_max 500',  ...
'SELECTED_OUTPUT 1',  ... 
   ' -file                 ex9.xls',  ... 
    '-reset                false',  ... 
    '-si           Fe_tri(OH)3(a) Goethite',... 
'USER_PUNCH 1',  ... 
   ' -headings Days Fe(2) Fe(3) pH O2  ',  ... 
    '-start',  ... 
'10 PUNCH SIM_TIME/3600/24,  TOT("Fe_di")*1000*55.847, TOT("Fe_tri")*1000*55.847,-LA("H+"),TOT("O(0)")*1000*16 ',  ... 
    '-end',  ... 
'END'};
IPCstring = sprintf('%s\n', IPCstringCell{:});
iphreeqc.RunString(IPCstring); % Run the string
che = iphreeqc.GetSelectedOutputArray;
end